export const ingList = [
  {
    name: "meats",
    examples: [
      "bacon",
      "beef",
      "chicken",
      "duck",
      "eggs",
      "ham",
      "pancetta",
      "pepperoni",
      "pork",
      "sausage",
      "steak",
      "turkey",
    ],
  },
  {
    name: "seafood",
    examples: [
      "clams",
      "crab",
      "fish",
      "lobster",
      "mackerel",
      "oysters",
      "prawns",
      "salmon",
      "sardines",
      "scallops",
      "shrimp",
      "tuna",
    ],
  },
  {
    name: "vegetables",
    examples: [
      "asparagus",
      "broccoli",
      "cabbage",
      "carrots",
      "cauliflower",
      "celery",
      "garlic",
      "ginger",
      "lettuce",
      "mushrooms",
      "olives",
      "onions",
      "potatoes",
      "spinach",
      "tomatoes",
    ],
  },
  {
    name: "fruits",
    examples: [
      "apples",
      "avocado",
      "bananas",
      "blueberries",
      "cherries",
      "grapes",
      "kiwis",
      "lemon",
      "lime",
      "oranges",
      "peaches",
      "pears",
      "pineapples",
      "strawberries",
      "watermelon",
    ],
  },
  {
    name: "baking",
    examples: [
      "baking soda",
      "brown sugar",
      "butter",
      "cornstarch",
      "flour",
      "sugar",
      "vanilla",
      "yeast",
    ],
  },

  {
    name: "canned/misc",
    examples: [
      "beans",
      "chicken broth",
      "corn",
      "olives",
      "peanut butter",
      "tomato paste",
      "tomato sauce",
      "tofu",
    ],
  },

  {
    name: "condiments",
    examples: [
      "fish sauce",
      "gochujang",
      "ketchup",
      "mayonnaise",
      "oyster sauce",
      "sesame oil",
      "sesame seeds",
      "soy sauce",
      "wasabi",
    ],
  },
  {
    name: "dairy",
    examples: [
      "butter",
      "cheese",
      "cream",
      "eggs",
      "ghee",
      "milk",
      "mozzarella",
      "parmesan",
      "sour cream",
      "yogurt",
    ],
  },

  {
    name: "grains",
    examples: [
      "cornmeal",
      "lentils",
      "oat",
      "quinoa",
      "rice",
      "rice paper",
      "spaghetti",
      "tortillas",
    ],
  },
  {
    name: "herbs",
    examples: [
      "basil",
      "cilantro",
      "dill",
      "mint",
      "oregano",
      "parsley",
      "rosemary",
      "thyme",
    ],
  },

  {
    name: "nuts and seeds",
    examples: [
      "almonds",
      "cashews",
      "chia seeds",
      "hazelnuts",
      "peanuts",
      "pecans",
      "pistachios",
      "pumpkin seeds",
      "sesame seeds",
      "walnuts",
    ],
  },
  {
    name: "oils and vinegars",
    examples: [
      "avocado oil",
      "balsamic",
      "canola oil",
      "coconut oil",
      "olive oil",
      "rice vinegar",
      "sesame oil",
      "vegetable oil",
      "white vinegar",
      "white wine",
    ],
  },

  {
    name: "spices",
    examples: [
      "black pepper",
      "chili powder",
      "cinnamon",
      "cumin",
      "garlic powder",
      "nutmeg",
      "oregano",
      "paprika",
      "turmeric",
    ],
  },
  {
    name: "sweets",
    examples: [
      "chocolate",
      "chocolate chips",
      "candy",
      "cookies",
      "gelatin",
      "maple syrup",
      "marshmallows",
      "sprinkles",
    ],
  },
];
