// export const ingList = [
//   {
//     name: "meats",
//     examples: ["beef", "chicken", "goat", "pork", "duck", "turkey", "eggs"],
//   },
//   {
//     name: "seafood",
//     examples: ["salmon", "tuna", "crab", "prawns", "scallops", "lobster"],
//   },
//   {
//     name: "vegetables",
//     examples: [
//       "asparagus",
//       "cauliflower",
//       "potatoes",
//       "tomatoes",
//       "onions",
//       "broccoli",
//       "garlic",
//       "carrots",
//       "mushrooms",
//       "cauliflower",
//       "cabbage",
//       "ginger",
//     ],
//   },
//   {
//     name: "fruits",
//     examples: [
//       "apples",
//       "avocados",
//       "grapes",
//       "bananas",
//       "strawberries",
//       "cherries",
//     ],
//   },
//   {
//     name: "dairy",
//     examples: [
//       "milk",
//       "yogurt",
//       "cream",
//       "coconut milk",
//       "cheese",
//       "cream cheese",
//     ],
//   },
//   {
//     name: "canned goods/misc",
//     examples: [
//       "tomato sauce",
//       "tomato paste",
//       "kidney beans",
//       "chickpeas",
//       "black beans",
//       "tofu",
//     ],
//   },

//   {
//     name: "baking",
//     examples: [
//       "flour",
//       "sugar",
//       "baking powder",
//       "baking soda",
//       "vanilla extract",
//       "butter",
//     ],
//   },
//   {
//     name: "herbs",
//     examples: ["dill", "parsley", "cilantro", "basil"],
//   },

//   {
//     name: "condiments",
//     examples: [
//       "soy sauce",
//       "oyster sauce",
//       "sesame oil",
//       "gochujang",
//       "fish sauce",
//       "seasame seeds",
//       "wasabi",
//     ],
//   },
//   {
//     name: "spices",
//     examples: [
//       "cumin",
//       "chili powder",
//       "oregano",
//       "paprika",
//       "basil",
//       "cayenne",
//     ],
//   },
//   {
//     name: "grains",
//     examples: [
//       "rice",
//       "pasta",
//       "sphaghetti",
//       "oat",
//       "tortillas",
//       "quinoa",
//       "rice paper",
//     ],
//   },
// ];

export const ingList = [
  {
    name: "meats",
    examples: [
      "bacon",
      "beef",
      "chicken",
      "duck",
      "eggs",
      "goat",
      "ham",
      "lamb",
      "pancetta",
      "pepperoni",
      "pork",
      "sausage",
      "steak",
      "turkey",
    ],
  },
  {
    name: "seafood",
    examples: [
      "clams",
      "crab",
      "fish",
      "lobster",
      "mackerel",
      "oysters",
      "prawns",
      "salmon",
      "sardines",
      "scallops",
      "shrimp",
      "tuna",
    ],
  },
  {
    name: "vegetables",
    examples: [
      "asparagus",
      "broccoli",
      "cabbage",
      "carrots",
      "cauliflower",
      "celery",
      "cucumbers",
      "garlic",
      "ginger",
      "lettuce",
      "mixed vegetables",
      "mushrooms",
      "olives",
      "onions",
      "potatoes",
      "spinach",
      "tomatoes",
      "zucchini",
    ],
  },
  {
    name: "fruits",
    examples: [
      "apples",
      "avocado",
      "bananas",
      "blueberries",
      "cherries",
      "grapes",
      "kiwis",
      "lemon",
      "lime",
      "oranges",
      "peaches",
      "pears",
      "pineapples",
      "strawberries",
      "watermelon",
    ],
  },
  {
    name: "baking",
    examples: [
      "almond extract",
      "baking powder",
      "baking soda",
      "brown sugar",
      "butter",
      "cocoa powder",
      "cornstarch",
      "flour",
      "powdered sugar",
      "sugar",
      "vanilla extract",
      "yeast",
    ],
  },

  {
    name: "canned goods/misc",
    examples: [
      "black beans",
      "chicken broth",
      "chickpeas",
      "coconut milk",
      "corn",
      "kidney beans",
      "olives",
      "peaches",
      "peanut butter",
      "tomato paste",
      "tomato sauce",
      "tofu",
      "vegetable broth",
    ],
  },

  {
    name: "condiments",
    examples: [
      "barbecue sauce",
      "fish sauce",
      "gochujang",
      "honey mustard",
      "ketchup",
      "mayonnaise",
      "oyster sauce",
      "sesame oil",
      "sesame seeds",
      "soy sauce",
      "wasabi",
      "worcesteshire sauce",
    ],
  },
  {
    name: "dairy",
    examples: [
      "butter",
      "cheese",
      "cream",
      "cream cheese",
      "eggs",
      "ghee",
      "milk",
      "mozzarella cheese",
      "parmesan cheese",
      "sour cream",
      "yogurt",
    ],
  },

  {
    name: "grains",
    examples: [
      "barley",
      "buckwheat",
      "cornmeal",
      "lentils",
      "oat",
      "pasta",
      "quinoa",
      "rice",
      "rice paper",
      "spaghetti",
      "tortillas",
    ],
  },
  {
    name: "herbs",
    examples: [
      "basil",
      "cilantro",
      "dill",
      "mint",
      "oregano",
      "parsley",
      "rosemary",
      "thyme",
    ],
  },

  {
    name: "nuts and seeds",
    examples: [
      "almonds",
      "cashews",
      "chia seeds",
      "flaxseeds",
      "hazelnuts",
      "peanuts",
      "pecans",
      "pine nuts",
      "pistachios",
      "pumpkin seeds",
      "sesame seeds",
      "sunflower seeds",
      "walnuts",
    ],
  },
  {
    name: "oils and vinegars",
    examples: [
      "avocado oil",
      "canola oil",
      "coconut oil",
      "olive oil",
      "sesame oil",
      "vegetable oil",
      "apple cider vinegar",
      "balsamic vinegar",
      "rice vinegar",
      "white vinegar",
      "white wine",
    ],
  },

  {
    name: "spices",
    examples: [
      "black pepper",
      "chili powder",
      "cinnamon",
      "cumin",
      "curry powder",
      "garlic powder",
      "nutmeg",
      "oregano",
      "paprika",
      "red pepper flakes",
      "turmeric",
    ],
  },
  {
    name: "sweets",
    examples: [
      "chocolate",
      "chocolate chips",
      "candy",
      "cookies",
      "gelatin",
      "maple syrup",
      "marshmallows",
      "sprinkles",
    ],
  },
];
